#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=eval_linp
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:50:00
#SBATCH --output=slurm_output_%A.out

cd ./mae
DATA_DIR=../FairVLMed/Dataset/dataset-001
FEATS_TYPE=image # [image, multimodal]

EXP_NAME=../results_pp/lin_prob/eval
MODEL_TYPE=clip # [clip, blip2]

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate fairclip

SEED=42
OMP_NUM_THREADS=1
PRETRAIN_CHKPT=./tmp_ft_42/best_checkpoint.pth

python -m torch.distributed.launch --master_port=29501 --nproc_per_node=1 main_linprobe.py \
	--model_type ${MODEL_TYPE} \
	--vl_feats_type ${FEATS_TYPE} \
	--blip_feats_select avgpool \
	--cfg-path ../LAVIS/lavis/projects/blip2/train/pretrain_stage1.yaml \
	--vision_encoder_weights clip \
	--summary_type gpt-4 \
	--batch_size 512 \
	--model vit_large_patch16 \
	--cls_token \
	--finetune ${PRETRAIN_CHKPT} \
	--epochs 1 \
	--blr 0.1 \
	--weight_decay 0.0 \
	--data_path ${DATA_DIR} \
	--nb_classes 2 \
	--output_dir ${EXP_NAME}_${SEED} \
	--log_dir ${EXP_NAME}_${SEED} \
	--seed ${SEED} \
	--eval

SEED=43
OMP_NUM_THREADS=1
PRETRAIN_CHKPT=./tmp_ft_43/best_checkpoint.pth
python -m torch.distributed.launch --master_port=29502 --nproc_per_node=1 main_linprobe.py \
        --model_type ${MODEL_TYPE} \
        --vl_feats_type ${FEATS_TYPE} \
        --blip_feats_select avgpool \
        --cfg-path ../LAVIS/lavis/projects/blip2/train/pretrain_stage1.yaml \
        --vision_encoder_weights clip \
        --summary_type gpt-4 \
        --batch_size 512 \
        --model vit_large_patch16 \
        --cls_token \
        --finetune ${PRETRAIN_CHKPT} \
        --epochs 1 \
        --blr 0.1 \
        --weight_decay 0.0 \
        --data_path ${DATA_DIR} \
        --nb_classes 2 \
        --output_dir ${EXP_NAME}_${SEED} \
        --log_dir ${EXP_NAME}_${SEED} \
        --seed ${SEED} \
        --eval

SEED=44
OMP_NUM_THREADS=1
PRETRAIN_CHKPT=./tmp_ft_44/best_checkpoint.pth
python -m torch.distributed.launch --master_port=29503 --nproc_per_node=1 main_linprobe.py \
        --model_type ${MODEL_TYPE} \
        --vl_feats_type ${FEATS_TYPE} \
        --blip_feats_select avgpool \
        --cfg-path ../LAVIS/lavis/projects/blip2/train/pretrain_stage1.yaml \
        --vision_encoder_weights clip \
        --summary_type gpt-4 \
        --batch_size 512 \
        --model vit_large_patch16 \
        --cls_token \
        --finetune ${PRETRAIN_CHKPT} \
        --epochs 1 \
        --blr 0.1 \
        --weight_decay 0.0 \
        --data_path ${DATA_DIR} \
        --nb_classes 2 \
        --output_dir ${EXP_NAME}_${SEED} \
        --log_dir ${EXP_NAME}_${SEED} \
        --seed ${SEED} \
        --eval
